
import java.sql.Connection;
import java.util.Date;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author meaya
 */
public class deposite extends javax.swing.JFrame {
static  String username;

public static  void setUserName(String u)
{
    username=u;
}
     public void transaction(String amount){
            {
                  try{
                       
                        Date date = new Date();  
                        SimpleDateFormat formatter = new SimpleDateFormat("dd/MM/yyyy");  
                        String strDate= formatter.format(date);  
                        Connection con=config.getconnection();
                        if(con.isValid(1)){
                        String sql= "insert into transaction values (?,?,?)";
                        PreparedStatement ps=con.prepareStatement(sql); 
                        ps.setString(1, strDate);
                        ps.setString(2, amount);
                        ps.setString(3, username);
                        int res=ps.executeUpdate();
                        if(res>0){
                            JOptionPane.showMessageDialog(rootPane, "sucessfull");
                            
                            
                        }else{
                            JOptionPane.showMessageDialog(rootPane, "not sucessfull");
                        }
                    }else{
                        JOptionPane.showMessageDialog(rootPane, "not connected");
                    }con.close();
                }
                     
                  catch (Exception e) {
                       JOptionPane.showMessageDialog(rootPane, e);
                    }
    }
    }
     
   public int pamount(){
        
         try{
         
                    Connection con= config.getconnection();
                    if(con.isValid(1))
                    {
                        String sql= "select principleamount from register where username=? ";
                        PreparedStatement ps=con.prepareStatement(sql);
                        ps.setString(1, username);
                        ResultSet resultSet=ps.executeQuery();
                        return Integer.parseInt(resultSet.getString("principleamount"));
                        
                        
                  }
            }catch(Exception e){
                        JOptionPane.showMessageDialog(rootPane, e);
                          }
         return 0;
         
       
   }
    public deposite() {
        initComponents();
    }

    /**
     *
     */
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("deposite ");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("enter amount :");

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("confirm");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(jLabel2)
                        .addGap(46, 46, 46)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(149, 149, 149)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(116, 116, 116)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(81, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addComponent(jButton1)
                .addGap(99, 99, 99))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
            String amount= String.valueOf(pamount()+Integer.parseInt( jTextField1.getText()));
            
            
             try{
                if(amount.isEmpty()){
                    JOptionPane.showMessageDialog(rootPane, "enter the info");
                }else{
                    Connection con=config.getconnection();
                    if(con.isValid(1)){
                        String sql= "UPDATE register set principleamount=? where username=?";
                        PreparedStatement ps=con.prepareStatement(sql);
                        ps.setString(1, amount);
                        ps.setString(2, username);
                        int res=ps.executeUpdate();
                        if(res>0){
                            JOptionPane.showMessageDialog(rootPane, "sucessfull");
                            jTextField1.setText("");
                              transaction(amount);    
                            
                        }else{
                            JOptionPane.showMessageDialog(rootPane, "not sucessfull");
                        }
                    }else{
                        JOptionPane.showMessageDialog(rootPane, "not connected");
                    } con.close();
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(rootPane, e);
            }
                 
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(deposite.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(deposite.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(deposite.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(deposite.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new deposite().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
